/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Product {
  'id' : bigint,
  'name' : string,
  'createdAt' : bigint,
  'description' : string,
  'affiliateUrl' : string,
  'isActive' : boolean,
  'imageUrl' : string,
  'category' : string,
  'price' : string,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addProduct' : ActorMethod<
    [string, string, string, string, string, string],
    bigint
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteProduct' : ActorMethod<[bigint], undefined>,
  'getAllActiveProducts' : ActorMethod<[], Array<Product>>,
  'getAllCategories' : ActorMethod<[], Array<string>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getProductsByCategory' : ActorMethod<[string], Array<Product>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'initialize' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'toggleProductActive' : ActorMethod<[bigint], undefined>,
  'updateProduct' : ActorMethod<
    [bigint, string, string, string, string, string, string],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];